version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    hostname: localhost
    environment:
      - MONGO_INITDB_DATABASE=favInfo
    ports:
      - 27017:27017